src/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('transactions/', include(('transactions.urls', 'transactions'), namespace='transactions')),
    path('habits/', include(('habits.urls', 'habits'), namespace='habits')),
    #path('journal/', include(('journal.urls', 'journal'), namespace="journal")),
    path('dashboard/logging/', include(('logging_app.urls', 'logging'), namespace='logging')),

    path('', include('website.urls', namespace='website')),
    path('', include('pwa.urls')),  # You MUST use an empty string as the URL prefix

    path('webpush/', include('webpush.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/website/urls.py
from django.urls import path
from . import views

app_name="website"
urlpatterns = [
    path('', views.base, name="home"),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('dashboard/image/', views.image_page, name='image_page'),
    path('dashboard/contact/', views.contact_page, name='contact_page'),
    path('dashboard/opening_hours/', views.opening_hours_page, name='opening_hours_page'),
    path('dashboard/gallery', views.gallery_page, name='gallery_page'),
    path('dashboard/add_image/', views.add_image, name='add_image'),
    path('dashboard/add_contact/', views.add_contact, name='add_contact'),
    path('dashboard/add_opening_hour/', views.add_opening_hour, name='add_opening_hour'),
    path('dashboard/add_gallery/', views.add_gallery, name='add_gallery'),
    path('delete_image/<int:image_id>/', views.delete_image, name='delete_image'),
    path('delete_contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('delete_opening_hours/<int:opening_hour_id>/', views.delete_opening_hour, name='delete_opening_hour'),
    path('delete_gallery/<int:gallery_id>/', views.delete_gallery, name='delete_gallery'),

    path('create_group/', views.create_group, name='create_group'),
    path('list_group/', views.group_list, name='list_group'),
    path('list_subscription/', views.subscription_list, name='list_subscription'),
]

src/website/models.py
from django.db import models
from django.utils.html import format_html
from django.conf import settings
import os

### information models
class Gallery(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Galleries'
        

    def get_images(self):
        return self.images.all()
    
    def __str__(self):
        return self.name
    

class Image(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='images', null=True, blank=True, help_text="Non necessario se non deve essere inserita in una galleria")
    description = models.CharField(max_length=300, default="", blank=True, null=True, help_text="identifica l'immagine")
    img = models.ImageField(upload_to="", blank=True, null=True)
    is_first = models.BooleanField(default=False, help_text="clicca se vuoi che sia la prima ad essere visualizzata in un eventuale galleria")


    def show_image(self):
        return format_html('<img src="{}" style="height:250px;" />', self.img.url)

    def __str__(self):
        return self.img.url
    
    def delete(self, *args, **kwargs):
        # Elimina il file dal server
        if self.img:
            path = os.path.join(settings.MEDIA_ROOT, str(self.img))
            os.remove(path)

        super().delete(*args, **kwargs)


class Contact(models.Model):
    phone = models.CharField(max_length=100, blank=True, null=True)
    mail = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return "Contacts"


class Opening_hour(models.Model):
    weekdays = models.CharField(max_length = 200, blank=True, null=True)
    weekend = models.CharField(max_length=300, blank=True, null=True)
    closing_day = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return "Opening hours"

src/website/forms.py
from django import forms
from .models import Image, Contact, Opening_hour, Gallery
from webpush.models import Group


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['gallery', 'description', 'img', 'is_first']
        widgets = {
            'description': forms.TextInput(attrs={'placeholder': 'Necessaria ad identificarla'}),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['phone', 'mail']
        widgets = {
            'phone': forms.TextInput(attrs={'placeholder': 'Inserisci il numero di telefono'}),
            'mail': forms.TextInput(attrs={'placeholder': 'Inserisci l\'indirizzo email'}),
        }


class OpeningHourForm(forms.ModelForm):
    class Meta:
        model = Opening_hour
        fields = ['weekdays', 'weekend', 'closing_day']
        widgets = {
            'weekdays': forms.TextInput(attrs={'placeholder': 'Inserisci gli orari settimanali'}),
            'weekend': forms.TextInput(attrs={'placeholder': 'Inserisci gli orari del weekend'}),
            'closing_day': forms.TextInput(attrs={'placeholder': 'Inserisci un giorno della settimana'}),
        }


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['name', 'images']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Non usare spazi nel nome'}),            
            'images': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    images = forms.ModelMultipleChoiceField(
        queryset=Image.objects.filter(gallery__isnull=True), 
        required=False
    )

    def save(self, commit=True):
        gallery = super().save(commit=False)
        if commit:
            gallery.save()

            # Associa le immagini selezionate alla galleria
            images = self.cleaned_data.get('images')
            if images:
                for image in images:
                    image.gallery = gallery
                    image.save()

        return gallery

src/website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.http import require_GET, require_POST
from django.http.response import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Image, Contact, Opening_hour, Gallery
from .forms import ImageForm, ContactForm, OpeningHourForm, GalleryForm
from django.contrib import messages

from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

from django.conf import settings

from webpush import send_group_notification, send_user_notification
from .forms import GroupForm
from webpush.models import Group, PushInformation

def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()  # Salva l'oggetto Group nel database
            return redirect('website:list_group')  # Reindirizza alla lista dei gruppi dopo la creazione
    else:
        form = GroupForm()
    return render(request, 'website/dashboard/create_group.html', {'form': form})


def group_list(request):
    groups = Group.objects.all()
    return render(request, 'website/dashboard/group_list.html', {'groups': groups})


def subscription_list(request):
    push_infos = PushInformation.objects.all()
    return render(request, 'website/dashboard/push_info.html', {'push_infos': push_infos})


    
# this is the part of the website accessible only to admin
@login_required
def dashboard(request):
    
    # Recupera tutte le istanze dei modelli
    gallery_images = Image.objects.all()
    contacts = Contact.objects.all()
    opening_hours = Opening_hour.objects.all()
    gallery = Gallery.objects.all()

    context = {
        'gallery_images': gallery_images,
        'contacts': contacts,
        'opening_hours': opening_hours,
        'gallery': gallery,
    }

    return render(request, 'website/dashboard/dashboard.html', context)

@login_required
def image_page(request):
    images = Image.objects.all()
    form = ImageForm()

    context = {
        'images': images,
        'form': form,
    }

    return render(request, 'website/dashboard/image_page.html', context)
    
@login_required
def add_image(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Immagine aggiunta con successo.')
            return redirect('website:image_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/image_page.html', {'form': form})
    else:
        form = ImageForm()

    return render(request, 'website/dashboard/image_page.html', {'form': form})

@login_required
def delete_image(request, image_id):
    # Trova l'immagine nel database
    image = get_object_or_404(Image, id=image_id)

    # Elimina l'immagine
    image.delete()
    messages.success(request, 'Immagine eliminata con successo.')
    return redirect('website:image_page')


@login_required
def gallery_page(request):
    galleries = Gallery.objects.all()
    form = GalleryForm()

    context = {
        'galleries': galleries,
        'form': form,
    }

    return render(request, 'website/dashboard/gallery_page.html', context)
    
@login_required
def add_gallery(request):
    print(request)
    if request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Galleria aggiunta con successo.')
            return redirect('website:gallery_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/gallery_page.html', {'form': form})
    else:
        form = ImageForm()

    return render(request, 'website/dashboard/gallery_page.html', {'form': form})

@login_required
def delete_gallery(request, gallery_id):
    # Trova l'immagine nel database
    gallery = get_object_or_404(Gallery, id=gallery_id)

    # Elimina l'immagine
    gallery.delete()
    messages.success(request, 'Galleria eliminata con successo.')
    return redirect('website:gallery_page')


@login_required
def contact_page(request):
    contacts = Contact.objects.all()
    form = ContactForm()
    context = {
        'contacts': contacts,
        'form':form,
    }

    return render(request, 'website/dashboard/contact_page.html', context)

@login_required
def add_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contatto aggiunto con successo.')
            return redirect('website:contact_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/contact_page.html', {'form': form})
    else:
        form = ContactForm()

    return render(request, 'website/dashboard/contact_page.html', {'form': form})

@login_required
def delete_contact(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id)
    contact.delete()
    messages.success(request, 'Contatto eliminato con successo.')
    return redirect('website:contact_page')


@login_required
def opening_hours_page(request):
    opening_hours = Opening_hour.objects.all()
    form = OpeningHourForm()
    context = {
        'opening_hours': opening_hours,
        'form':form,
    }

    return render(request, 'website/dashboard/opening_hours_page.html', context)

@login_required
def add_opening_hour(request):
    if request.method == 'POST':
        form = OpeningHourForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Orario aggiunto con successo. Ricorda di cambiare gli orari anche su Google.')
            return redirect('website:opening_hours_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/opening_hours_page.html', {'form': form})
    else:
        form = OpeningHourForm()

    return render(request, 'website/dashboard/opening_hours_page.html', {'form': form})

@login_required
def delete_opening_hour(request, opening_hour_id):
    hours = get_object_or_404(Opening_hour, pk=opening_hour_id)
    hours.delete()
    messages.success(request, 'Orario eliminato con successo.')
    return redirect('website:opening_hours_page')



def base(request):
    # Verifica se l'utente esiste prima di tentare di inviare la notifica
    #try:
    #    user = User.objects.get(username=request.user.username)
    #except User.DoesNotExist:
        # Gestione nel caso l'utente non esista
        # Ad esempio, mostra un messaggio di errore o esegui un'altra azione
    #    return render(request, 'website/landing.html', {'error_message': 'L\'utente specificato non esiste'})

    # Costruisci il payload della notifica
    #payload = {
    #    "head": "Benvenuto!  " + user.username,
    #    "body": "Ciao Mondo",
    #    "icon": "https://i.imgur.com/dRDxiCQ.png",
    #    "url": "https://www.example.com"
    #}

    # Invia la notifica all'utente specificato
    #send_user_notification(user=user, payload=payload, ttl=1000)

    # Ritorna la risposta al render della pagina di destinazione
    return render(request, 'website/landing.html')#, {'success_message': 'Notifica inviata con successo'})

src/website/templates/website/dashboard/contact_page.html
{% extends "website/dashboard/dashboard.html" %}
{% load static %}
{% block dashboard_app %}
<div class="container mt-5">
    <div class="row">
        <!-- Form per l'aggiunta di un contatto -->
        {% if not contacts %}
            <div class="col-md-6">
                <h2>Aggiungi Contatto</h2>
                <form action="{% url 'website:add_contact' %}" hx-target="#main-content" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Aggiungi</button>
                </form>
            </div>
        {% else %}

        <!-- Lista dei contatti -->
        <div class="col-md-6">
            <h2>Contatti</h2>
            <p class="mb-1">Telefono: {{ contacts.0.phone }}</p>
            <p class="mb-1">Email: {{ contacts.0.mail }}</p>
            <form action="{% url 'website:delete_contact' contacts.0.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Elimina</button>
            </form> 
        </div>
        {% endif %}
    </div>
</div>
{% endblock dashboard_app %}

src/website/templates/website/dashboard/create_group.html
{% extends "website/dashboard/dashboard.html" %}
{% load static %}
{% block dashboard_app %}
<div class="container mt-5">
    <div class="row">
        <h1>Crea un nuovo Gruppo</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Salva</button>
        </form>
    </div>
</div>
{% endblock dashboard_app %}

src/website/templates/website/dashboard/dashboard.html
{% extends "website/base.html" %}
{% load static %}
{% load webpush_notifications %}
{% block content %}
  <h1 class="ms-3"> Dashboard </h1>
  <div class="container-fluid mt-5">
    <div class="row">
      <nav id="sidebar" class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
        <div class="position-sticky">
          
          <ul class="nav flex-column">

            <!-- INIZIO GESTIONE WEBPUSH-->
            <li class="nav-item">
              <a class="nav-link active" data-bs-toggle="collapse" href="#webpushAccordion" role="button" aria-expanded="true" aria-controls="webpushAccordion">
                Notifications
              </a>
              <div class="collapse" id="webpushAccordion">
                <ul class="nav flex-column ms-3">
                  <li class="nav-item">
                      {% webpush_button with_class="btn btn-primary btn-sm" %}
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:create_group' %}">Create group</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:list_group' %}">List notifications Groups</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:list_subscription' %}">List subscriptions</a>
                  </li>
                </ul>
              </div>
            </li>
            <!-- FINE GESTIONE WEBPUSH-->

            <!-- INIZIO DELL'APPLICAZIONE WEBSITE-->
            <li class="nav-item">
              <a class="nav-link active" data-bs-toggle="collapse" href="#menuAccordion" role="button" aria-expanded="true" aria-controls="menuAccordion">
                Website
              </a>
              <div class="collapse" id="menuAccordion">
                <ul class="nav flex-column ms-3">
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:image_page' %}" >Immagini</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:contact_page' %}">Contatti</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:opening_hours_page' %}">Orari di Apertura</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'website:gallery_page' %}">Galleria</a>
                  </li>
                </ul>
              </div>
            </li>
            <!-- FINE DELL'APPLICAZIONE WEBSITE-->


            <!-- INIZIO DELL'APPLICAZIONE LOGGING -->
            {% include 'logging_app/accordion.html' %}
            <!-- FINE DELL'APPLICAZIONE LOGGING -->
            

            <!-- Aggiungi qui i modelli delle altre applicazioni
                ATTENZIONE A COPIARE E INCOLLARE devi cambiare 
                href e id del menuaccordion
                -->
            
          </ul>
        </div>
      </nav>

      <main id="main-content" class="
              col-md-9 
              ms-sm-auto 
              col-lg-10 
              px-md-4">
              {% block dashboard_app %}
            
              {% endblock dashboard_app %}
      </main>
    </div>
  </div>
{% endblock content %}

src/website/templates/website/dashboard/gallery_page.html
{% extends "website/dashboard/dashboard.html" %}
{% load static %}
{% block dashboard_app %}
<div class="d-flex flex-column justify-content-center align-items-center">
    <!-- Button per aprire il form -->
    <button class="btn btn-primary mt-3" type="button" data-bs-toggle="collapse" data-bs-target="#addGalleryForm" aria-expanded="false" aria-controls="addImageForm">
        <i class="fa-solid fa-plus"></i>
    </button>


    <!-- Form per l'aggiunta di un'immagine (nascosto per default) -->
    <div class="collapse mt-3 w-100" id="addGalleryForm">
        <form action="{% url 'website:add_gallery' %}" method="post" >
            {% csrf_token add_gallery_csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Aggiungi</button>
        </form>
    </div>
    
    <!-- Lista delle immagini -->
    <div id="gallery-list" class="col-12 p-5 ">
        {% if galleries %}
            <h2> Lista delle gallerie </h2>
            <ul class="list-unstyled">
                {% for gallery in galleries %}
                    <li class="mb-4 p-3">
                        <div class="d-flex align-items-center justify-content-around card">
                            <div class="">
                                <h5> Nome: {{ gallery.name }}</h5>
                                <form action="{% url 'website:delete_gallery' gallery.id %}" method="post" style="display: inline;">
                                    {% csrf_token delete_gallery_csrf_token %}
                                    <button type="submit" class="btn btn-danger">Elimina</button>
                                </form>
                                <p> Eliminando la galleria si eliminano tutte le foto legate ad essa. </p>
                            </div>
                            
                            {% if gallery.get_images %}
                            <div>
                                <button class="carousel-control-prev" type="button" data-bs-target="#carousel{{gallery.name}}" data-bs-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Previous</span>
                                </button>
                                <div class="carousel slide carousel-fade" data-bs-interval="false"  id="carousel{{gallery.name}}">
                                    <div class="carousel-inner">
                                        {% for img in gallery.get_images %}
                                            <div class="carousel-item{% if forloop.first %} active{% endif %}">
                                                {{ img.show_image }}
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                                <button class="carousel-control-next" type="button" data-bs-target="#carousel{{gallery.name}}" data-bs-slide="next">
                                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                    <span class="visually-hidden">Next</span>
                                </button>
                            </div>
                            {% else %}
                                <p> Non ci sono foto in questa galleria.
                            {% endif %}
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Non sono presenti gallerie al momento.</p>
        {% endif %}
    </div>
</div> 
<style>
/* Personalizza il colore delle frecce del carousel */
.carousel-control-prev-icon,
.carousel-control-next-icon {
     filter: invert(1); /* Cambia il colore delle frecce a nero */
}
</style>
{% endblock dashboard_app %}

src/website/templates/website/dashboard/group_list.html
{% extends "website/dashboard/dashboard.html" %}
{% load static %}
{% block dashboard_app %}
<div class="container mt-5">
    <div class="row">
        <h1>Elenco dei Gruppi</h1>
        <ul class="list-group mt-4">
            {% for group in groups %}
                <!-- Utilizza la classe "list-group-item" di Bootstrap per ogni elemento della lista -->
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ group }} - {{ group.name }}
                    
                </li>
            {% endfor %}
        </ul>
        
    </div>
</div>
{% endblock dashboard_app %}

src/website/templates/website/dashboard/image_page.html
{% extends "website/dashboard/dashboard.html" %}
{% load static %}
{% block dashboard_app %}
                   
<div class="d-flex flex-column justify-content-center align-items-center">
    <!-- Button per aprire il form -->
    <button class="btn btn-primary mt-3" type="button" data-bs-toggle="collapse" data-bs-target="#addImageForm" aria-expanded="false" aria-controls="addImageForm">
        <i class="fa-solid fa-plus"></i>
    </button>

    <!-- Nel tuo template 'website/dashboard/image_page.html' -->
    <div class="collapse mt-3 w-100" id="addImageForm">
        <form action="{% url 'website:add_image' %}" method="post" enctype="multipart/form-data">
            {% csrf_token add_image_csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Aggiungi</button>
        </form>
    </div>

    <!-- Lista delle immagini -->
    <div id="image-list" class="col-12 p-5 ">
        {% if images %}
            <h2> Lista delle immagini </h2>
            <ul  class="list-unstyled">
                {% for image in images %}
                    <li class="mb-4 p-3">
                        <div class="d-flex">
                            <!-- Immagine a sinistra -->
                            <div class="col-md-4">
                                <img src="{{ image.img.url }}" alt="{{ image.description }}" style="max-width: 100px; height: auto;">
                            </div>
                            <!-- Dettagli e form a destra -->
                            <div class="col-md-6">
                                <div>
                                    <p>Nome: {{ image.description }}</p>
                                    <p>Galleria: {{ image.gallery }}</p>
                                </div>
                                <form action="{% url 'website:delete_image' image.id %}" method="post" style="display: inline;">
                                    {% csrf_token delete_image_csrf_token %}
                                    <button type="submit" class="btn btn-danger">Elimina</button>
                                </form>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Non sono presenti immagini al momento.</p>
        {% endif %}
    </div>
</div> 


{% endblock dashboard_app %}

src/website/templates/website/dashboard/opening_hours_page.html
{% extends "website/dashboard/dashboard.html" %}
{% load static %}
{% block dashboard_app %}
<div class="container mt-5">
    <div class="row">
        {% if not opening_hours %}
            <!-- Se non esiste un modello di Opening Hour -->
            <div class="col-md-6">
                <h2>Aggiungi Orario Apertura</h2>
                <form action="{% url 'website:add_opening_hour' %}" method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Aggiungi</button>
                </form>
            </div>
        {% else %}
            <!-- Se esiste già un modello di Opening Hour -->
            <div class="col-md-6">
                <h2>Orario Apertura</h2>
                <p>Settimana: {{ opening_hours.0.weekdays }}</p>
                <p>Weekend: {{ opening_hours.0.weekend }}</p>
                <p>Giorno di Chiusura: {{ opening_hours.0.closing_day }}</p>
                <!-- Form per eliminare il modello -->
                <form action="{% url 'website:delete_opening_hour' opening_hours.0.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Elimina</button>
                </form>
            </div>
        {% endif %}
    </div>
</div>

{% endblock dashboard_app %}

src/website/templates/website/dashboard/push_info.html
{% extends "website/dashboard/dashboard.html" %}
{% load static %}
{% block dashboard_app %}
<div class="container mt-5">
    <div class="row">
        <h1>Elenco delle sottoscrizioni</h1>
        <ul class="list-group mt-4">
            {% for push_info in push_infos %}
                <!-- Utilizza la classe "list-group-item" di Bootstrap per ogni elemento della lista -->
                <li class="list-group-item d-flex justify-content-between align-items-center">
                   <strong>User:</strong> {{ push_info.user }}  <strong>Subscription:</strong> {{ push_info.subscription }}  <strong>Group:</strong> {{ push_info.group }}
                </li>
            {% endfor %}
        </ul>
        
    </div>
</div>
{% endblock dashboard_app %}