src/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('transactions/', include(('transactions.urls', 'transactions'), namespace='transactions')),
    path('habits/', include(('habits.urls', 'habits'), namespace='habits')),
    #path('journal/', include(('journal.urls', 'journal'), namespace="journal")),
    path('dashboard/logging/', include(('logging_app.urls', 'logging'), namespace='logging')),

    path('', include('website.urls', namespace='website')),
    path('', include('pwa.urls')),  # You MUST use an empty string as the URL prefix

    path('webpush/', include('webpush.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/website/urls.py
from django.urls import path
from . import views

app_name="website"
urlpatterns = [
    path('', views.base, name="home"),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('dashboard/image/', views.image_page, name='image_page'),
    path('dashboard/contact/', views.contact_page, name='contact_page'),
    path('dashboard/opening_hours/', views.opening_hours_page, name='opening_hours_page'),
    path('dashboard/gallery', views.gallery_page, name='gallery_page'),
    path('dashboard/add_image/', views.add_image, name='add_image'),
    path('dashboard/add_contact/', views.add_contact, name='add_contact'),
    path('dashboard/add_opening_hour/', views.add_opening_hour, name='add_opening_hour'),
    path('dashboard/add_gallery/', views.add_gallery, name='add_gallery'),
    path('delete_image/<int:image_id>/', views.delete_image, name='delete_image'),
    path('delete_contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
    path('delete_opening_hours/<int:opening_hour_id>/', views.delete_opening_hour, name='delete_opening_hour'),
    path('delete_gallery/<int:gallery_id>/', views.delete_gallery, name='delete_gallery'),

    path('create_group/', views.create_group, name='create_group'),
    path('list_group/', views.group_list, name='list_group'),
    path('list_subscription/', views.subscription_list, name='list_subscription'),
]

src/website/models.py
from django.db import models
from django.utils.html import format_html
from django.conf import settings
import os

### information models
class Gallery(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Galleries'
        

    def get_images(self):
        return self.images.all()
    
    def __str__(self):
        return self.name
    

class Image(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE, related_name='images', null=True, blank=True, help_text="Non necessario se non deve essere inserita in una galleria")
    description = models.CharField(max_length=300, default="", blank=True, null=True, help_text="identifica l'immagine")
    img = models.ImageField(upload_to="", blank=True, null=True)
    is_first = models.BooleanField(default=False, help_text="clicca se vuoi che sia la prima ad essere visualizzata in un eventuale galleria")


    def show_image(self):
        return format_html('<img src="{}" style="height:250px;" />', self.img.url)

    def __str__(self):
        return self.img.url
    
    def delete(self, *args, **kwargs):
        # Elimina il file dal server
        if self.img:
            path = os.path.join(settings.MEDIA_ROOT, str(self.img))
            os.remove(path)

        super().delete(*args, **kwargs)


class Contact(models.Model):
    phone = models.CharField(max_length=100, blank=True, null=True)
    mail = models.CharField(max_length=50, blank=True, null=True)
    
    def __str__(self):
        return "Contacts"


class Opening_hour(models.Model):
    weekdays = models.CharField(max_length = 200, blank=True, null=True)
    weekend = models.CharField(max_length=300, blank=True, null=True)
    closing_day = models.CharField(max_length=200, blank=True, null=True)
    
    def __str__(self):
        return "Opening hours"

src/website/forms.py
from django import forms
from .models import Image, Contact, Opening_hour, Gallery
from webpush.models import Group


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['gallery', 'description', 'img', 'is_first']
        widgets = {
            'description': forms.TextInput(attrs={'placeholder': 'Necessaria ad identificarla'}),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['phone', 'mail']
        widgets = {
            'phone': forms.TextInput(attrs={'placeholder': 'Inserisci il numero di telefono'}),
            'mail': forms.TextInput(attrs={'placeholder': 'Inserisci l\'indirizzo email'}),
        }


class OpeningHourForm(forms.ModelForm):
    class Meta:
        model = Opening_hour
        fields = ['weekdays', 'weekend', 'closing_day']
        widgets = {
            'weekdays': forms.TextInput(attrs={'placeholder': 'Inserisci gli orari settimanali'}),
            'weekend': forms.TextInput(attrs={'placeholder': 'Inserisci gli orari del weekend'}),
            'closing_day': forms.TextInput(attrs={'placeholder': 'Inserisci un giorno della settimana'}),
        }


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['name', 'images']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Non usare spazi nel nome'}),            
            'images': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    images = forms.ModelMultipleChoiceField(
        queryset=Image.objects.filter(gallery__isnull=True), 
        required=False
    )

    def save(self, commit=True):
        gallery = super().save(commit=False)
        if commit:
            gallery.save()

            # Associa le immagini selezionate alla galleria
            images = self.cleaned_data.get('images')
            if images:
                for image in images:
                    image.gallery = gallery
                    image.save()

        return gallery

src/website/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views.decorators.http import require_GET, require_POST
from django.http.response import JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Image, Contact, Opening_hour, Gallery
from .forms import ImageForm, ContactForm, OpeningHourForm, GalleryForm
from django.contrib import messages

from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt

from django.conf import settings

from webpush import send_group_notification, send_user_notification
from .forms import GroupForm
from webpush.models import Group, PushInformation

def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            form.save()  # Salva l'oggetto Group nel database
            return redirect('website:list_group')  # Reindirizza alla lista dei gruppi dopo la creazione
    else:
        form = GroupForm()
    return render(request, 'website/dashboard/create_group.html', {'form': form})


def group_list(request):
    groups = Group.objects.all()
    return render(request, 'website/dashboard/group_list.html', {'groups': groups})


def subscription_list(request):
    push_infos = PushInformation.objects.all()
    return render(request, 'website/dashboard/push_info.html', {'push_infos': push_infos})


    
# this is the part of the website accessible only to admin
@login_required
def dashboard(request):
    
    # Recupera tutte le istanze dei modelli
    gallery_images = Image.objects.all()
    contacts = Contact.objects.all()
    opening_hours = Opening_hour.objects.all()
    gallery = Gallery.objects.all()

    context = {
        'gallery_images': gallery_images,
        'contacts': contacts,
        'opening_hours': opening_hours,
        'gallery': gallery,
    }

    return render(request, 'website/dashboard/dashboard.html', context)

@login_required
def image_page(request):
    images = Image.objects.all()
    form = ImageForm()

    context = {
        'images': images,
        'form': form,
    }

    return render(request, 'website/dashboard/image_page.html', context)
    
@login_required
def add_image(request):
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Immagine aggiunta con successo.')
            return redirect('website:image_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/image_page.html', {'form': form})
    else:
        form = ImageForm()

    return render(request, 'website/dashboard/image_page.html', {'form': form})

@login_required
def delete_image(request, image_id):
    # Trova l'immagine nel database
    image = get_object_or_404(Image, id=image_id)

    # Elimina l'immagine
    image.delete()
    messages.success(request, 'Immagine eliminata con successo.')
    return redirect('website:image_page')


@login_required
def gallery_page(request):
    galleries = Gallery.objects.all()
    form = GalleryForm()

    context = {
        'galleries': galleries,
        'form': form,
    }

    return render(request, 'website/dashboard/gallery_page.html', context)
    
@login_required
def add_gallery(request):
    print(request)
    if request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Galleria aggiunta con successo.')
            return redirect('website:gallery_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/gallery_page.html', {'form': form})
    else:
        form = ImageForm()

    return render(request, 'website/dashboard/gallery_page.html', {'form': form})

@login_required
def delete_gallery(request, gallery_id):
    # Trova l'immagine nel database
    gallery = get_object_or_404(Gallery, id=gallery_id)

    # Elimina l'immagine
    gallery.delete()
    messages.success(request, 'Galleria eliminata con successo.')
    return redirect('website:gallery_page')


@login_required
def contact_page(request):
    contacts = Contact.objects.all()
    form = ContactForm()
    context = {
        'contacts': contacts,
        'form':form,
    }

    return render(request, 'website/dashboard/contact_page.html', context)

@login_required
def add_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Contatto aggiunto con successo.')
            return redirect('website:contact_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/contact_page.html', {'form': form})
    else:
        form = ContactForm()

    return render(request, 'website/dashboard/contact_page.html', {'form': form})

@login_required
def delete_contact(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id)
    contact.delete()
    messages.success(request, 'Contatto eliminato con successo.')
    return redirect('website:contact_page')


@login_required
def opening_hours_page(request):
    opening_hours = Opening_hour.objects.all()
    form = OpeningHourForm()
    context = {
        'opening_hours': opening_hours,
        'form':form,
    }

    return render(request, 'website/dashboard/opening_hours_page.html', context)

@login_required
def add_opening_hour(request):
    if request.method == 'POST':
        form = OpeningHourForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Orario aggiunto con successo. Ricorda di cambiare gli orari anche su Google.')
            return redirect('website:opening_hours_page')
        else:
            messages.error(request, 'Si è verificato un errore. Si prega di correggere il modulo.')
            return render(request, 'website/dashboard/opening_hours_page.html', {'form': form})
    else:
        form = OpeningHourForm()

    return render(request, 'website/dashboard/opening_hours_page.html', {'form': form})

@login_required
def delete_opening_hour(request, opening_hour_id):
    hours = get_object_or_404(Opening_hour, pk=opening_hour_id)
    hours.delete()
    messages.success(request, 'Orario eliminato con successo.')
    return redirect('website:opening_hours_page')



def base(request):
    # Verifica se l'utente esiste prima di tentare di inviare la notifica
    #try:
    #    user = User.objects.get(username=request.user.username)
    #except User.DoesNotExist:
        # Gestione nel caso l'utente non esista
        # Ad esempio, mostra un messaggio di errore o esegui un'altra azione
    #    return render(request, 'website/landing.html', {'error_message': 'L\'utente specificato non esiste'})

    # Costruisci il payload della notifica
    #payload = {
    #    "head": "Benvenuto!  " + user.username,
    #    "body": "Ciao Mondo",
    #    "icon": "https://i.imgur.com/dRDxiCQ.png",
    #    "url": "https://www.example.com"
    #}

    # Invia la notifica all'utente specificato
    #send_user_notification(user=user, payload=payload, ttl=1000)

    # Ritorna la risposta al render della pagina di destinazione
    return render(request, 'website/landing.html')#, {'success_message': 'Notifica inviata con successo'})

src/website/templates/website/base.html
{% load static %}
{% load pwa %}
{% load webpush_notifications %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <title>{% block title %} {% endblock title %}</title>
        <meta name="description" content="">

        <link rel="icon" href="{% static 'favicon/bee.ico' %}" type="image/png">

        <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css"/>
        <script src="https://unpkg.com/htmx.org@1.6.0/dist/htmx.min.js"></script>

        <!-- Quill -->
        <link rel="stylesheet" href="https://cdn.quilljs.com/1.3.6/quill.snow.css">
        <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>


        {% progressive_web_app_meta %}
        {% webpush_header %}

    </head>
    <body> 
    {% include 'website/navbar.html' %}
    
    <!-- modal for messages -->
    {% if messages %}
        <div class="alert {% if message.tags == 'error' %}alert-danger{% else %}alert-info{% endif %} alert-dismissible fade show position-fixed bottom-0 end-0 m-4 z-index-3" role="alert">
            {% for message in messages %}
                {{ message }}
                {% if not forloop.last %}<br>{% endif %}
            {% endfor %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}



    {% block content %}

    {% endblock content %}
        

    {% include 'website/footer.html' %}

        
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>
    </body>
</html>

src/website/templates/website/footer.html
<style>
    .text-orange{
        color: #FFD180;
    }
</style>
<footer class="py-5 mt-5 bg-dark text-orange">
    <div class="container">
        <div class="row m-5">
            <div class="col-6">
                <h5>Site Map</h5>
                <ul class="nav flex-column">
                    <li class="nav-item mb-0"><a class="p-0 nav-link text-decoration-none text-orange" href="{% url 'website:home' %}">HOME</a></li>
                    <li class="nav-item mb-0"><a class="p-0 nav-link text-decoration-none text-orange" href="{% url 'transactions:index' %}">Transactions</a></li>
                    
                    <li class="nav-item mb-0"><a class="p-0 nav-link text-decoration-none text-orange" href="#">Screener</a></li>
                    <li class="nav-item mb-0"><a class="p-0 nav-link text-decoration-none text-orange" href="{% url 'habits:index' %}">Habits</a></li>
                </ul>
            </div>
            <div class="col-6">
                <h5>Admin links</h5>
                <ul class="nav flex-column">
                    <li class="ms-1"><a class="d-flex align-items-center text-decoration-none text-orange" href="{% url 'admin:index' %}">Admin</a></li>
                    {% if user.is_authenticated %}
                        <li class="ms-1">
                            <a class="d-flex align-items-center text-decoration-none text-orange" href="{% url 'logout' %}">
                                Logout from account: {{ user.username }}
                            </a>
                            </form>
                            <a class="d-flex align-items-center text-decoration-none text-orange" href="{% url 'website:dashboard' %}">
                                Dashboard
                            </a>
                        </li>
                    {% else %}
                        <li class="ms-1">
                            <a class="d-flex align-items-center text-decoration-none text-orange" href="{% url 'login' %}">
                                Login
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

    <div class="bg-dark text-white py-3">
        <div class="container flex-sm-row flex-column d-flex justify-content-between align-items-center">
            <p class="fs-6 m-0 ">Website created by Leonardo Bitto</p>
            <p class="m-0 ">Contact me at leonardobitto@gmail.com</p>
            <ul class="list-unstyled d-flex">
                <li class="ms-3">
                    <a class="d-flex align-items-center text-decoration-none " href="https://github.com/leoBitto" target="_blank">
                    <?xml version="1.0" encoding="UTF-8"?>
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="30px" height="48px" viewBox="0 0 49 48" version="1.1">
                        <g id="surface1">
                            <path style="stroke:none;fill-rule:evenodd;fill:#FFF;fill-opacity:1;" d="M 24.425781 0 C 10.917969 0 0 11 0 24.609375 C 0 35.488281 6.996094 44.695312 16.703125 47.953125 C 17.914062 48.199219 18.359375 47.425781 18.359375 46.773438 C 18.359375 46.203125 18.320312 44.246094 18.320312 42.210938 C 11.527344 43.675781 10.109375 39.277344 10.109375 39.277344 C 9.019531 36.421875 7.402344 35.691406 7.402344 35.691406 C 5.175781 34.183594 7.5625 34.183594 7.5625 34.183594 C 10.03125 34.347656 11.324219 36.710938 11.324219 36.710938 C 13.507812 40.457031 17.027344 39.398438 18.441406 38.746094 C 18.644531 37.15625 19.289062 36.058594 19.976562 35.445312 C 14.558594 34.875 8.855469 32.757812 8.855469 23.304688 C 8.855469 20.617188 9.828125 18.414062 11.363281 16.703125 C 11.121094 16.09375 10.273438 13.566406 11.605469 10.183594 C 11.605469 10.183594 13.667969 9.535156 18.320312 12.710938 C 20.3125 12.171875 22.363281 11.898438 24.425781 11.898438 C 26.488281 11.898438 28.59375 12.183594 30.535156 12.710938 C 35.183594 9.535156 37.246094 10.183594 37.246094 10.183594 C 38.582031 13.566406 37.730469 16.09375 37.488281 16.703125 C 39.066406 18.414062 39.996094 20.617188 39.996094 23.304688 C 39.996094 32.757812 34.296875 34.835938 28.835938 35.445312 C 29.726562 36.21875 30.492188 37.6875 30.492188 40.007812 C 30.492188 43.308594 30.453125 45.957031 30.453125 46.773438 C 30.453125 47.425781 30.898438 48.199219 32.109375 47.953125 C 41.816406 44.695312 48.8125 35.488281 48.8125 24.609375 C 48.851562 11 37.894531 0 24.425781 0 Z M 24.425781 0 "/>
                        </g>
                    </svg>
                    </a>
                </li>
                <li class="ms-3">
                    <a class="d-flex align-items-center text-decoration-none " href="https://www.linkedin.com/in/leonardo-bitto/" target="_blank">
                    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 48 48" style="enable-background:new 0 0 48 48; width: 30px; height: 48px;" xml:space="preserve" fill="#FFF">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
                        <g id="SVGRepo_iconCarrier"> <g> <g> <path style="fill:#0288D1;" d="M42,37c0,2.762-2.238,5-5,5H11c-2.761,0-5-2.238-5-5V11c0-2.762,2.239-5,5-5h26c2.762,0,5,2.238,5,5V37z"></path>
                        <path style="fill:#FFF;" d="M12 19H17V36H12zM14.485 17h-.028C12.965 17 12 15.888 12 14.499 12 13.08 12.995 12 14.514 12c1.521 0 2.458 1.08 2.486 2.499C17 15.887 16.035 17 14.485 17zM36 36h-5v-9.099c0-2.198-1.225-3.698-3.192-3.698-1.501 0-2.313 1.012-2.707 1.99C24.957 25.543 25 26.511 25 27v9h-5V19h5v2.616C25.721 20.5 26.85 19 29.738 19c3.578 0 6.261 2.25 6.261 7.274L36 36 36 36z"></path></g> </g> </g>
                    </svg>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</footer>

<script>
$(document).ready(function() {
    $('#logout-form a').click(function(e) {
        e.preventDefault();
        $('#logout-form').submit();
    });
});
</script>

src/website/templates/website/landing.html
{% extends "website/base.html" %}
{% load static %}
{% block title %}Homepage{% endblock title %}
{% block content %}

<style>
    .app-section {
        background-color: #FFD180;
        border-radius: 8px;
        text-align: center;
    }

    .btn-custom {
        background-color: #FF6347;
        border-color: #FF6347;
        color: #fff;
    }
</style>

<div class="container">
    <div class="row">
        <div class="col-md-6 mb-4">
            <div class=" m-1 p-2 app-section">
                <i class="fas fa-exchange-alt m-2"></i>
                <a href="{% url 'transactions:index' %}" class="btn btn-custom btn-sm"> Transactions</a>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class=" m-1 p-2 app-section">
                <i class="fas fa-chart-bar m-2"></i>
                <a href="" class="btn btn-custom btn-sm"> Screener</a>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class=" m-1 p-2 app-section">
                <i class="fas fa-heart m-2"></i>
                <a href="{% url 'habits:index' %}" class="btn btn-custom btn-sm"> Habits</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/website/templates/website/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg" style="background-color: #FFD180;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'website:home' %}">
            <img src="{% static 'icons/bee.png' %}" alt="Home" width="30" height="30" class="d-inline-block align-text-top">
            HOME
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'transactions:index' %}">
                        <i class="fas fa-exchange-alt"></i> Transactions
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="#">
                        <i class="fas fa-chart-bar"></i> Screener
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'habits:index' %}">
                        <i class="fas fa-heart"></i> Habits
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>